package vincent.assignment1.controller.suggestionControl;

import android.app.Activity;
import android.util.Log;

import java.util.List;

import vincent.assignment1.model.SimpleTrackable;

import static vincent.assignment1.view.MainActivity.TAG_STAGE;

/**
 * @author Yu Liu
 *
 * a signleten class, it is used to communicate among different classes;
 * there is another option is to use intent and Parcelable which can pass object between activity
 */

public class SuggestionControl {

    private static SuggestionControl Instance;

    private String curLocation;
    private List<SimpleTrackable> availableList;
    private Activity activity;
    private List<SimpleTrackable> suggestedList;
    private List<SimpleTrackable> mutableList;

    public SuggestionControl (){
    }


    public static SuggestionControl getInstance(){
        if(Instance == null){
            Instance = new SuggestionControl();
        }
        return Instance;
    }

    public void setLocation (Activity activity, String location){
        if(this.activity == null){
            this.activity = activity;
        }
        this.curLocation = location;
    }

    public List<SimpleTrackable> getMutableList(){

        if(mutableList == null){
            Log.d(TAG_STAGE + getClass().getName(),"getMutableList is called");
            this.mutableList = this.suggestedList;
        }else if ( mutableList.size() == 0){
            this.mutableList = this.suggestedList;
        }

        Log.d(TAG_STAGE + getClass().getName(), "mutableList size :" + mutableList.size());
        return this.mutableList;
    }


    //only be called at first time as it check activity. probably merge with "updateAvailableList()"
    public void setAvailableList (Activity activity, List<SimpleTrackable> availableList){
        if(this.activity == null){
            this.activity = activity;
        }
        this.availableList = availableList;
    }


    //update the available list when the trackable list are changed when user select category
    public void updateAvailableList ( List<SimpleTrackable> availableList) {
        this.availableList = availableList;
    }

    public void setSuggestedList (){
        this.suggestedList = getSuggestedList();
        Log.d(TAG_STAGE + getClass().getName(), "SuggestedList size: " + suggestedList.size());
    }

    //return suggested list which are generated by specific algorithm
    public List<SimpleTrackable> getSuggestedList() {
        SuggestionTrackableManager manager = new SuggestionTrackableManager(activity, availableList);

        DistanceMatrixManager distanceMatrixManager = new DistanceMatrixManager(activity, curLocation, manager.getRouteInfo());

        return distanceMatrixManager.getFinalSuggestionList(distanceMatrixManager.getResponseList());
    }
}
